name: Build Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install NDK & CMake
      run: |
        sdkmanager --install "ndk;26.1.10909125"
        sdkmanager --install "cmake;3.22.1"
        
    - name: Build Release
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        retention-days: 1

    - name: Upload SO files
      uses: actions/upload-artifact@v4
      with:
        name: native-libraries
        path: app/build/intermediates/cmake/release/obj/**/liblicense.so
        retention-days: 1
